version: '3'

services:
  greenmail:
    image: greenmail/standalone:2.1.0-alpha-3
    ports:
      - "3025:3025"
      - "3110:3110"
      - "3143:3143"
      - "3465:3465"
      - "3993:3993"
      - "3995:3995"
      - "8080:8080"
    environment:
      GREENMAIL_OPTS: "-Dgreenmail.setup.test.all -Dgreenmail.hostname=0.0.0.0 -Dgreenmail.auth.disabled"
      JAVA_OPTS: "-Djava.net.preferIPv4Stack=true"
